# Site settings
title: Bill E. Dawson
email: info@bedawson.com
description: Email geek. Speaker. Techie. User Advocate.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://billedawson.github.io"
github_username:  billedawson

# Build settings
markdown: kramdown