# Site settings
title: Bill E. Dawson
email: info@bedawson.com
description: Educator. Startup Coach. Angel Investor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://billedawson.github.io"
twitter_username:  billedawson
linkedin_username:  billedawson

include:
  - _pages

# Build settings
markdown: kramdown